In [23]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split

from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

In [3]:
df = pd.read_excel("hr_employee_data.xlsx")

In [4]:

df.head()

,Emp_Id,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,IND02438,0.38,0.53,2,157,3,0,1,0,sales,low
1,IND28133,0.80,0.86,5,262,6,0,1,0,sales,medium
2,IND07164,0.11,0.88,7,272,4,0,1,0,sales,medium
3,IND30478,0.72,0.87,5,223,5,0,1,0,sales,low
4,IND24003,0.37,0.52,2,159,3,0,1,0,sales,low

In [5]:
df.describe()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000
mean,0.612834,0.716102,3.803054,201.050337,3.498233,0.144610,0.238083,0.021268
std,0.248631,0.171169,1.232592,49.943099,1.460136,0.351719,0.425924,0.144281
min,0.090000,0.360000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000
25%,0.440000,0.560000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000
50%,0.640000,0.720000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000
75%,0.820000,0.870000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000

In [7]:
print(df.isnull().sum())

Emp_Id                   0
satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [8]:
x = df.drop("left", axis=1)
y = df["left"]

In [10]:
print (x)

         Emp_Id  satisfaction_level  last_evaluation  number_project  \
0      IND02438                0.38             0.53               2
1      IND28133                0.80             0.86               5
2      IND07164                0.11             0.88               7
3      IND30478                0.72             0.87               5
4      IND24003                0.37             0.52               2
...         ...                 ...              ...             ...
14994  IND40221                0.40             0.57               2
14995  IND24196                0.37             0.48               2
14996  IND33544                0.37             0.53               2
14997  IND40533                0.11             0.96               6
14998  IND11649                0.37             0.52               2

       average_montly_hours  time_spend_company  Work_accident  \
0                       157                   3              0
1                       262                   6              0
2                       272                   4              0
3                       223                   5              0
4                       159                   3              0
...                     ...                 ...            ...
14994                   151                   3              0
14995                   160                   3              0
14996                   143                   3              0
14997                   280                   4              0
14998                   158                   3              0

       promotion_last_5years Department  salary
0                          0      sales     low
1                          0      sales  medium
2                          0      sales  medium
3                          0      sales     low
4                          0      sales     low
...                      ...        ...     ...
14994                      0    support     low
14995                      0    support     low
14996                      0    support     low
14997                      0    support     low
14998                      0    support     low

[14999 rows x 10 columns]

In [11]:
print(y)

0        1
1        1
2        1
3        1
4        1
        ..
14994    1
14995    1
14996    1
14997    1
14998    1
Name: left, Length: 14999, dtype: int64

In [14]:
x = pd.get_dummies(x,columns=["Department", "salary"],dtype=int)

In [16]:
x.head(5)

,Emp_Id,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Department_IT,Department_RandD,...,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium
0,IND02438,0.38,0.53,2,157,3,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,IND28133,0.80,0.86,5,262,6,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,IND07164,0.11,0.88,7,272,4,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,IND30478,0.72,0.87,5,223,5,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4,IND24003,0.37,0.52,2,159,3,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [21]:
x= x.drop("Emp_Id" , axis =1)

In [ ]:
x.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,Department_IT,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_high,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
1,0.80,0.86,5,262,6,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
2,0.11,0.88,7,272,4,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,0.72,0.87,5,223,5,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0.37,0.52,2,159,3,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0

In [26]:
X_train_full, X_test, y_train_full, y_test = train_test_split(x, y, test_size=0.2, random_state=40)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.3, random_state=36)

In [28]:
svm = Pipeline([
    ('scaler', StandardScaler()),
    ('svc', SVC()),
])

svm_params = {
    'svc__C': (0.1, 1, 10, 100),
    'svc__gamma': ('scale', 0.01, 0.1, 1),
    'svc__kernel': ('linear', 'rbf'),
}

svm_grid = GridSearchCV(svm, svm_params)
svm_grid.fit(X_train, y_train)
svm_pred = svm_grid.predict(X_val)

In [ ]:
# Now we retrain our model on the train + validation data. 
Svm_final = Pipeline([
    ('scaler', StandardScaler()),
    ('svc', SVC(C=100, gamma=0.01, kernel='rbf')),
]).fit(X_train_full, y_train_full)
pred_test = Svm_final.predict(X_test)